# Introduction to NumPy and Matrix Algebra

If you have not installed **NumPy** yet, please follow the steps to install it first: https://numpy.org/install/

If you can successfully run the following cell, let's start our journey to Linear Algebra powered by **NumPy**.

In [4]:
import numpy as np

You will learn about some functions of NumPy and Matrix Algebra through this Notebook.

# An overview on **NumPy**

**NumPy** is one of the core libraries for scientific computing in Python, providing powerful tools for working with multidimensional arrays. The collection of high-performance functions in NumPy enables efficient operations on arrays, such as mathematical computations, logical operations, shape manipulation, sorting, selection, input/output handing, discrete Fourier transforms, linear algebra, statistical analysis, random number generation, and more.

Further reading and documentation about **NumPy**: https://numpy.org/doc/stable/

# Matrix Notation

Consider a system of linear equations (or linear system):

\begin{align*}
x_1 - 2x_2 + x_3 &= 0 \\
2x_2 - 8x_3 &= 8 \\
5x_1 - 5x_3 &= 10
\end{align*}

The linear system above is realigned as follows, so yhe essential information of the system can be recorded compactly in a rectangular array called a matrix. Given the system

\begin{array}{rcl}
x_1 & - 2x_2 & + x_3 = 0 \\
     & 2x_2  & - 8x_3 = 8 \\
5x_1 &        & - 5x_3 = 10
\end{array}

### Create a Coefficient Matrix

To create a matrix, the function `np.array()` is used. The prefix `np` is used here because the `array()` function is a function inside of **NumPy** module.

In [17]:
# NumPy Array (np.array()) is used to create a matrix
C = np.array([[1, -2, 1], [0, 2, -8], [5, 0, -5]])

In [19]:
print(C)

[[ 1 -2  1]
 [ 0  2 -8]
 [ 5  0 -5]]


### Create a Augmented Matrix

In [22]:
A = np.array([[1, -2, 1, 0], [0, 2, -8, 8], [5, 0, -5, 10]])

In [24]:
print(A)

[[ 1 -2  1  0]
 [ 0  2 -8  8]
 [ 5  0 -5 10]]


### Size of a Matrix

The size of a matrix is accessed using  `.shape` in NumPy (In **MATLAB**, the size of a matrix is obtained using the  `size()` function.)

In [28]:
C.shape

(3, 3)

In [30]:
A.shape

(3, 4)

# Vector Notation

A matrix with only one column is called a column vector, or simply a vector.

For a vector, you only need to input on `[ ]` inside `np.array()`.

In [34]:
# Create 2-dimensional vectors: u and v
u = np.array([1, -2])
v = np.array([2, -5])

Vector (in $n$ -dimension) is represented as a matrix whose number of rows is $n$ and number of column is always zero.

In [37]:
u.shape

(2,)

In [39]:
v.shape

(2,)

In [41]:
# Vector addition
print(u + v)

[ 3 -7]


In [43]:
# Scalar multiplication
print(4 * u)
print(-3 * v)

[ 4 -8]
[-6 15]


# Matrix Operations

### Sums and Scalar Multiples

In [47]:
# Create three matrices: A, B, C
A = np.array([[4, 0, 5], [-1, 3, 2]])
B = np.array([[1, 1, 1], [3, 5, 7]])
C = np.array([[2, -3], [0, 1]])

In [49]:
# A + B
A + B

array([[5, 1, 6],
       [2, 8, 9]])

In [51]:
# A + B in an alternative way
np.add(A, B)

array([[5, 1, 6],
       [2, 8, 9]])

In [53]:
# A - B
A - B

array([[ 3, -1,  4],
       [-4, -2, -5]])

In [55]:
# A - B in an alternative way
np.subtract(A, B)

array([[ 3, -1,  4],
       [-4, -2, -5]])

In [57]:
# A + C is not defined because A and C have different sizes
A + C

ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

In [59]:
 A.shape != C.shape

True

In [61]:
# Scalar multiplication
2 * B

array([[ 2,  2,  2],
       [ 6, 10, 14]])

In [63]:
# Scalar multiplication in an alternative way
np.multiply(2, B)

array([[ 2,  2,  2],
       [ 6, 10, 14]])

In [65]:
# Sum and Scalar multiplication
A - 2 * B

array([[  2,  -2,   3],
       [ -7,  -7, -12]])

In [67]:
# Sum and Scalar multiplication
np.subtract(A, 2 * B)

array([[  2,  -2,   3],
       [ -7,  -7, -12]])

In [69]:
# Sum and Scalar multiplication
np.subtract(A, np.multiply(2, B))

array([[  2,  -2,   3],
       [ -7,  -7, -12]])

### Matrix Multiplication

The symbol `@` is used as the sign for matrix multiplication.

In [73]:
# Create two matrices: M1, M2
M1 = np.array([[2, 3], [1, -5]])
M2 = np.array([[4, 3, 6],[1, -2, 3]])

In [75]:
# Matrix multiplication
M1@M2

array([[11,  0, 21],
       [-1, 13, -9]])

In [77]:
# Matrix multiplication in an alternative way
np.matmul(M1, M2)

array([[11,  0, 21],
       [-1, 13, -9]])

In [79]:
# Create two matrices: M3, M4
M3 = np.array([[5, 1], [3, -2]])
M4 = np.array([[2, 0], [4, 3]])

In [81]:
# In general, two matrices do not commute with each other
M3@M4

array([[14,  3],
       [-2, -6]])

In [83]:
M4@M3

array([[10,  2],
       [29, -2]])

In [85]:
M3@M4 != M4@M3

array([[ True,  True],
       [ True,  True]])

### The Transpose of a Matrix

The symbol `T` is used as the sign for matrix transpose. 

It is consistent with the textbook symbol.

In [89]:
print(A)

[[ 4  0  5]
 [-1  3  2]]


In [91]:
print(B)

[[1 1 1]
 [3 5 7]]


In [93]:
# Transpose of Matrix A
A.T

array([[ 4, -1],
       [ 0,  3],
       [ 5,  2]])

In [95]:
# Transpose of Matrix A in an alternative way
np.transpose(A)

array([[ 4, -1],
       [ 0,  3],
       [ 5,  2]])

#### Theorems of Matrix Transpose

$({A^T})^T = A$

In [99]:
# Transpose of Transpose of Matrix A is Matrix A
A.T.T

array([[ 4,  0,  5],
       [-1,  3,  2]])

In [101]:
A == A.T.T

array([[ True,  True,  True],
       [ True,  True,  True]])

$(A + B)^T = {A^T} + {B^T}$

In [104]:
(A + B).T

array([[5, 2],
       [1, 8],
       [6, 9]])

In [106]:
A.T + B.T

array([[5, 2],
       [1, 8],
       [6, 9]])

In [108]:
(A + B).T == A.T + B.T

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

For any scalar: $(rA)^T = rA^T$

The `np.random.rand()` function generates a random number (floats) between 0 and 1.

In [112]:
# randomly assign a number to r
# run this cell a few times, and you will see everytime the value of r is different
r = np.random.rand()
print(r)

0.7539934421558185


In [114]:
(r * A).T

array([[ 3.01597377, -0.75399344],
       [ 0.        ,  2.26198033],
       [ 3.76996721,  1.50798688]])

In [116]:
r * (A.T)

array([[ 3.01597377, -0.75399344],
       [ 0.        ,  2.26198033],
       [ 3.76996721,  1.50798688]])

In [118]:
(r * A).T == r * (A.T)

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

$(AB)^T = B^T  A^T $

To make sure the column of Matrix $A$ is equal to the row of Matrix $B$

In [122]:
# Redefine Matrix B
B = B.T

In [124]:
print(B)

[[1 3]
 [1 5]
 [1 7]]


In [126]:
(A@B).T

array([[ 9,  4],
       [47, 26]])

In [128]:
(B.T)@(A.T)

array([[ 9,  4],
       [47, 26]])

In [130]:
(A@B).T == (B.T)@(A.T)

array([[ True,  True],
       [ True,  True]])

### The Inverse of a Matrix

In [133]:
print(A)

[[ 4  0  5]
 [-1  3  2]]


$A^{-1}A = I \quad \text{and} \quad AA^{-1} = I$


A matrix that is not invertible is sometimes called a $\textit{singular matrix}$, and an invertible matrix is called a $\textit{non-singular matrix}$.

The inverse of a matrix in **NumPy** requires call the linear algebra submodule `np.linalg`. 

For more information on the documentation of functions within the submodule, please refer: https://numpy.org/doc/stable/reference/routines.linalg.html#routines-linalg

In [138]:
# Inverse of Matrix A
# singular matrix
print(np.linalg.inv(A))

LinAlgError: Last 2 dimensions of the array must be square

In [140]:
A_square = np.array([[2, 5],[-3, -7]])

In [142]:
print(A_square)

[[ 2  5]
 [-3 -7]]


In [144]:
print(np.linalg.inv(A_square))

[[-7. -5.]
 [ 3.  2.]]


In [146]:
A_square_inv = np.linalg.inv(A_square)

In [148]:
A_square@A_square_inv

array([[ 1.00000000e+00, -1.77635684e-15],
       [ 0.00000000e+00,  1.00000000e+00]])

#### What do you observe from the above operation? 


#### Why do you think the result is not the 2-by-2 Identity Matrix?

### Identity Matrix $\it I$

The Identity Matrix can be created by calling the `np.eye()` function.

It is consistent with the `eye()` function in **MATLAB**.

In [153]:
# 2-by-2 Matrix
I = np.eye(2)

In [155]:
print(I)

[[1. 0.]
 [0. 1.]]


Check the identity $\quad AA^{-1} = I$

In [158]:
A_square@A_square_inv == I

array([[False, False],
       [ True,  True]])

Here, we introduce the `np.allclose` to check the equation.

In [161]:
np.allclose(A_square@A_square_inv,I)

True

#### Theorems of Matrix Inverse

$\left(A^{-1}\right)^{-1} = A$

In [165]:
print(A_square)

[[ 2  5]
 [-3 -7]]


In [167]:
print(A_square_inv)

[[-7. -5.]
 [ 3.  2.]]


In [169]:
print(np.linalg.inv(A_square_inv))

[[ 2.  5.]
 [-3. -7.]]


In [171]:
np.allclose(A_square, np.linalg.inv(A_square_inv))

True

$(AB)^{-1} = B^{-1}A^{-1}$

In [174]:
B_square = np.array([[3, 4],[5, 6]])

In [176]:
AB_inv = np.linalg.inv(A_square@B_square)
print(AB_inv)

[[ 27.   19. ]
 [-22.  -15.5]]


In [178]:
B_square_inv = np.linalg.inv(B_square)
print(B_square_inv@A_square_inv)

[[ 27.   19. ]
 [-22.  -15.5]]


In [180]:
np.allclose(AB_inv,B_square_inv@A_square_inv)

True

$(A^T)^{-1} = (A^{-1})^T$

In [183]:
A_square_inv_t = np.linalg.inv(A_square.T)
print(A_square_inv_t)

[[-7.  3.]
 [-5.  2.]]


In [185]:
A_square_t_inv = (np.linalg.inv(A_square)).T
print(A_square_t_inv)

[[-7.  3.]
 [-5.  2.]]


In [187]:
np.allclose(A_square_inv_t,A_square_t_inv)

True

### Dimension and Rank of Matrix

In [190]:
H = np.array([[3, 6, 2], [-1, 0, 1], [3, 12, 7]])
print(H)

[[ 3  6  2]
 [-1  0  1]
 [ 3 12  7]]


In [192]:
# Dimension of Matrix H
H.ndim

2

In [194]:
# Rank of Matrix H
np.linalg.matrix_rank(H)

2

## Determinants

The determinant of a \$2 \times 2\$ matrix is defined as follows:

$A = \begin{bmatrix} a_{11} & a_{12} \\ a_{21} & a_{22} \end{bmatrix}$

$\det(A) = a_{11}a_{22} - a_{12}a_{21}$

In [198]:
print(A_square)

[[ 2  5]
 [-3 -7]]


In [200]:
A_square_det = np.linalg.det(A_square)

In [202]:
print(A_square_det)

1.0000000000000018


The determinant of a \$3 \times 3\$ matrix is defined as follows:

$A = \begin{bmatrix} a_{11} & a_{12} & a_{13} \\ a_{21} & a_{22} & a_{23} \\ a_{31} & a_{32} & a_{33} \end{bmatrix}$

$\det(A) = a_{11} \begin{vmatrix} a_{22} & a_{23} \\ a_{32} & a_{33} \end{vmatrix} - a_{12} \begin{vmatrix} a_{21} & a_{23} \\ a_{31} & a_{33} \end{vmatrix} + a_{13} \begin{vmatrix} a_{21} & a_{22} \\ a_{31} & a_{32} \end{vmatrix}.$

In [205]:
A_33 = np.array([[1, 5, 0], [2, 4, -1], [0, -2, 0]])
print(A_33)

[[ 1  5  0]
 [ 2  4 -1]
 [ 0 -2  0]]


In [207]:
A_33_det = np.linalg.det(A_33)

In [209]:
print(A_33_det)

-1.9999999999999998


Due to the numerical inaccuracies (this is an advanced topic on the algorithm behind `np.linalg.det()`), we need to use `round()` function to get the right result.

In [212]:
A_square_det_round = round(np.linalg.det(A_square))
print(A_square_det_round)

1


In [214]:
A_33_det_round = round(np.linalg.det(A_33))
print(A_33_det_round)

-2


## Try the following exercies by yourself:

1. Construct a linear system (at least three variables) and create the coefficient matrix and augmented matrix.

2. Construct a few n-dimensional vector (n > 2) and test the rules of operation among those vectors.

3. Construct a few matrices and test the rules of operation among those matrices.

4. Construct an invertible matrix, and calculate the dimension, the rank, and the determinant of it.


# Reference: 

David C. Lay et al., (2016) Linear Algebra and its Applications, fifth edition, Pearson 

Some examples are taken from Chapter 1 and Chapter 4 of the reference book.