In [1]:
import numpy as np

# Iterative Algorithm

## Overview

Consider the system of linear equation $A \mathbf{x} = \bf{b}$, assume that $A$ is a [square matrix](https://en.wikipedia.org/wiki/Square_matrix) and that there is a unique solution $\mathbf{x}$. When there are a large number of unknowns (like in the PageRank system for a network having millions of web pages), we begin with a guess at the solution, and then we iteratively improve the guess until it becomes sufficiently close to the actual solution. The main idea is to split the matrix $A$ into two parts by choosing some matrix $M$ of the same size as $A$ and writing:

\begin{align*}
A = M - (M - A)
\end{align*}

Plugging this into our original equation $A \bf{x} = \bf{b}$ and rearranging terms, we arrive at the equivalent system

\begin{align*}
M \mathbf{x} = (M - A)\mathbf{x} + \bf{b}
\end{align*}

We start with an initial guess 𝒙0 for the solution vector and then generate a sequence of refined guesses $\mathbf{x_1}$, $\mathbf{x_2}$, $\mathbf{x_3}$, ... using the iteration formula:

\begin{align*}
M \mathbf{x_k} = (M - A)\mathbf{x_{k-1}} + \bf{b}
\end{align*}

or index values $k$ = 1, 2, 3, ... . At each iteration, we solve the linear system for the unknown vector
$\mathbf{x_k}$ given that we have already computed $\mathbf{x_{k-1}}$. If we ever achieve the equality $\mathbf{x_k} = \mathbf{x_{k-1}}$ for some value of $k$, then we can stop because this means 𝒙𝑘 must be a solution. This rarely happens, however; instead, we hope that the entries in $\mathbf{x_k}$ get closer and closer to those in $\mathbf{x_{k-1}}$ as$k$ increases. When this happens we say that the sequence of guesses converges to a true solution, in which case we stop at some value of $k$ large enough for the guess $\mathbf{x_k}$ to be a “good enough” approximate solution.

## Jacobi’s method

In Jacobi’s method, we choose $M$ to be the diagonal part of $A$ (sometimes $M$ is written as $D$ to represent the diagonal matrix)

\begin{align*}
D_{ij} = 
\begin{cases} 
A_{ij} & \text{if } i = j, \\
0 & \text{if } i \neq j.
\end{cases}
\end{align*}

Thee solution to the equation, i.e. the value of $\mathbf{x}$, is given by the following iterative equation:

\begin{align*}
D \mathbf{x_k} = (D - A)\mathbf{x_{k-1}} + \bf{b}
\end{align*}

\begin{align*}
\mathbf{x_k} = D^{-1} [(D - A)\mathbf{x_{k-1}} + \bf{b}]
\end{align*}

In some text, $D-A$ is represented in matrix $-R$, where $R$ follows:

\begin{align*}
R_{ij} = 
\begin{cases} 
0 & \text{if } i = j, \\
A_{ij} & \text{if } i \neq j.
\end{cases}
\end{align*}

\begin{align*}
\mathbf{x_k} = D^{-1}(\mathbf{b} - R\mathbf{x_{k-1}})
\end{align*}

In [21]:
def jacobi(A, b, tolerance=1e-10, max_iterations=10000, x=None):
    """
    Solves the equation Ax=b via the Jacobi iterative method.

    Parameters:
    A : numpy.ndarray
        Coefficient matrix (must be square).
    b : numpy.ndarray
        Constant terms vector.
    tolerance : float, optional
        Convergence tolerance. The iteration stops when the relative difference
        between consecutive solutions is less than this value.
    max_iterations : int, optional
        Maximum number of iterations to perform.
    x : numpy.ndarray, optional
        Initial guess for the solution. If None, will start with a zero vector.

    Returns:
    x : numpy.ndarray
        Approximate solution after convergence or max_iterations.
    """
    # Initialize the initial guess if not provided
    if x is None:
        x = np.zeros(len(b))
        
    # Create the matrix R by subtracting the diagonal of A from A
    R = A - np.diag(np.diagonal(A))
    # Alternative wat
    # R = A - np.diagflat(np.diag(A))

    # Iterate for a maximum of max_iterations times
    for k in range(max_iterations):
        # Store the previous solution to check for convergence
        x_old = x.copy()

        # Update the solution vector using the Jacobi formula
        x[:] = (b - np.dot(R, x)) / np.diagonal(A)

        # Check for convergence using the relative error with infinity norm
        if np.linalg.norm(x - x_old, ord=np.inf) / np.linalg.norm(x, ord=np.inf) < tolerance:
            break
    
    return x

Recall PageRank Case:

In [24]:
H = np.array([[0, 0, 1/2, 1/3, 1/2], 
             [1/2, 0, 0, 1/3, 1/2], 
             [0, 1, 0, 1/3, 0],
             [0, 0, 1/2, 0, 0],
             [1/2, 0, 0, 0, 0]])

In [26]:
print(H)

[[0.         0.         0.5        0.33333333 0.5       ]
 [0.5        0.         0.         0.33333333 0.5       ]
 [0.         1.         0.         0.33333333 0.        ]
 [0.         0.         0.5        0.         0.        ]
 [0.5        0.         0.         0.         0.        ]]


In [28]:
d = 0.9

In [30]:
# The identity matrix in this case is a 5-by-5 identity matrix
I = np.eye(5)

In [32]:
one = np.ones(5)

In [34]:
r = jacobi(A = I - d * H, b =  (1 - d) * one, max_iterations = 15, x = one)

In [36]:
print(r)

[1.19608029 1.13515718 1.33139892 0.69914336 0.63822025]


In [38]:
highest_rank = max(r)

In [40]:
print(f'The highest rank is {highest_rank}.')

The highest rank is 1.3313989243462654.


In [42]:
print(f'The highest rank is about {round(highest_rank, 2)}.')

The highest rank is about 1.33.


## Gauss-Seidel method

In the Gauss-Seidel method, we choose $M$ to be the lower triangular part of $A$ including the diagonal ($M$ is then denoted as $L$), that is, $L$ is the same as $A$ along and below and including the main diagonal but is zero everywhere else.

\begin{align*}
L \mathbf{x_k} = (L - A)\mathbf{x_{k-1}} + \bf{b}
\end{align*}

The equation can be re-organized to the following format:

\begin{align*}
L \mathbf{x_k} =  \bf{b} -U \mathbf{x_{k-1}}
\end{align*}

where $U$ is the upper triangular part of $A$

\begin{align*}
\mathbf{x_k} = L^{-1}(\mathbf{b} - U\mathbf{x_{k-1}})
\end{align*}

In [51]:
def gauss_seidel(A, b, tol=1e-10, max_iterations=10000, x=None):
    """
    Solve the linear system Ax = b using the Gauss-Seidel iterative method.

    Parameters:
        A (ndarray): Coefficient matrix (n x n).
        b (ndarray): Constant terms vector (n).
        tol (float): Tolerance for convergence (default is 1e-10).
        max_iterations (int): Maximum number of iterations (default is 1000).
        x (ndarray): Initial guess for the solution vector (n) (default is None, initializes with zeros).

    Returns:
        x (ndarray): Solution vector (n).
    """
    n = len(b)
    if x is None:
        x = np.zeros(n)  # Initialize the solution vector with zeros if no initial guess is provided
    else:
        x = x.copy()  # Ensure the initial guess is not modified outside the function
    
    # Decompose A into L (lower triangular part) and U (upper triangular part)
    L = np.tril(A)  # Lower triangular matrix including the diagonal
    U = A - L  # Upper triangular matrix without the diagonal
    
    # Iterate to solve the system
    for k in range(max_iterations):
        x_old = x.copy()  # Store the previous iteration values
        
        # Update each element of the solution vector
        for i in range(n):
            # Calculate the sum of the known values in L and U matrices
            sum1 = np.dot(L[i, :i], x[:i])  # Sum of L * x for previous elements
            sum2 = np.dot(U[i, :], x_old)  # Sum of U * x_old for remaining elements
            # Update the current element of the solution vector
            if L[i, i] == 0:
                raise ValueError("Zero on diagonal. The matrix is singular and cannot be solved using Gauss-Seidel.")
            x[i] = (b[i] - sum1 - sum2) / L[i, i]
                
        # Check for convergence
        if np.linalg.norm(x - x_old, ord=np.inf) < tol:
            return x  # Converged, return the solution 
    
    # If the method did not converge within the maximum iterations, raise an error
    raise ValueError("Gauss-Seidel method did not converge within the maximum number of iterations")

In [53]:
rgs = gauss_seidel(A = I - d * H, b =  (1 - d) * one, max_iterations = 15, x = one)

ValueError: Gauss-Seidel method did not converge within the maximum number of iterations

In [55]:
print(I - d * H)

[[ 1.    0.   -0.45 -0.3  -0.45]
 [-0.45  1.    0.   -0.3  -0.45]
 [ 0.   -0.9   1.   -0.3   0.  ]
 [ 0.    0.   -0.45  1.    0.  ]
 [-0.45  0.    0.    0.    1.  ]]


The key reason why the Gauss-Seidel method struggles to converge while the Jacobi method succeeds is due to the above matrix is not [diagonally dominant](https://en.wikipedia.org/wiki/Diagonally_dominant_matrix).

\begin{align*}
{\displaystyle |a_{ii}| \geq \sum _{j\neq i}|a_{ij}|\ \ \forall \ i}
\end{align*}

where $a_{ij}$ denotes the entry in the $i$-th row and $j$-th column.

This lack of dominance makes the Gauss-Seidel method susceptible to divergence or oscillatory behavior.

## Gauss-Seidel method with relaxation

We introduce a relaxation facotr $\omega$. Adjusting the relaxation factor to a value less than 1 ($\omega$ < 1, i.e., under-relaxation) may stabilize the iterations. 

In [63]:
def gauss_seidel(A, b, tol=1e-8, max_iterations=10000, x=None, omega=1.0):
    """
    Solve the linear system Ax = b using the Gauss-Seidel iterative method with relaxation.

    Parameters:
        A (ndarray): Coefficient matrix (n x n).
        b (ndarray): Constant terms vector (n).
        tol (float): Tolerance for convergence (default is 1e-8).
        max_iterations (int): Maximum number of iterations (default is 5000).
        x (ndarray): Initial guess for the solution vector (n) (default is None, initializes with zeros).
        omega (float): Relaxation factor (default is 1.0).

    Returns:
        x (ndarray): Solution vector (n).
    """
    n = len(b)
    if x is None:
        x = np.zeros(n)  # Initialize the solution vector with zeros if no initial guess is provided
    else:
        x = x.copy()  # Ensure the initial guess is not modified outside the function
    
    # Decompose A into L (lower triangular part) and U (upper triangular part)
    L = np.tril(A)  # Lower triangular matrix including the diagonal
    U = A - L  # Upper triangular matrix without the diagonal
        
    # Iterate to solve the system
    for k in range(max_iterations):
        x_old = x.copy()  # Store the previous iteration values
        
        # Update each element of the solution vector
        for i in range(n):
            # Calculate the sum of the known values in L and U matrices
            sum1 = np.dot(L[i, :i], x[:i])  # Sum of L * x for previous elements
            sum2 = np.dot(U[i, :], x_old)  # Sum of U * x_old for remaining elements
            # Update the current element of the solution vector with relaxation
            if L[i, i] == 0:
                raise ValueError("Zero on diagonal. The matrix is singular and cannot be solved using Gauss-Seidel.")
            x[i] = (1 - omega) * x_old[i] + omega * (b[i] - sum1 - sum2) / L[i, i]
                
        # Check for convergence
        if np.linalg.norm(x - x_old, ord=np.inf) < tol:
            return x  # Converged, return the solution
    
    # If the method did not converge within the maximum iterations, raise an error
    raise ValueError("Gauss-Seidel method did not converge within the maximum number of iterations")

In [65]:
rgsr = gauss_seidel(A = I - d * H, b =  (1 - d) * one, max_iterations = 15, x = one, omega = 0.5)

ValueError: Gauss-Seidel method did not converge within the maximum number of iterations

It turns out the relaxation factor does not help much in this case. For Jacobi method, it calculates the next iteration using the values from the previous iteration for all variables, making it more robust for non-diagonally dominant matrices. However, Gauss-Seidel method updates each element immediately, which may amplify errors in matrices that do not meet the diagonal dominance requirement.

## Try the following exercies by yourself:

1. Try to create systems of equations and implement these two methods to solve those systems.

2. Try dufferent values for iterations and relaxation factors and compare the solutions of Jacobi method and Gauss-Seidel method.